El conjunto de datos es un archivo CSV llamado `f500.csv`. Aquí hay un diccionario de datos para algunas de las columnas en el CSV:

- `company`: El nombre de la empresa.
- `rank`: Ranking Global 500 para la empresa.
- `revenue`: Ingresos totales de la empresa para el año fiscal, en millones de dólares (USD).
- `revenue_change`: cambio porcentual en los ingresos entre el año fiscal actual y el anterior.
- `profits`: Utilidad neta del ejercicio, en millones de dólares (USD).
- `ceo`: Director General de la empresa.
- `industry`: La industria de operación de la empresa.
- `sector`: Sector en el que opera la empresa.
- `previous_rank`: Clasificación Global 500 de la empresa para el año anterior.
- `country`: País de la sede de la empresa.
- `hq_location`: ciudad y país (o ciudad y estado para EE. UU.) donde tiene su sede la empresa.
- `employees`: Total de empleados (equivalente a tiempo completo, si está disponible) al cierre del año fiscal.

In [18]:
import numpy as np
import pandas as pd

In [6]:
f500 = pd.read_csv('f500.csv',index_col=0)
f500.head()

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
company,,,,,,,,,,,,,,,,
Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers,Retailing,1,USA,"Bentonville, AR",http://www.walmart.com,23,2300000,77798
State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities,Energy,2,China,"Beijing, China",http://www.sgcc.com.cn,17,926067,209456
Sinopec Group,3,267518,-9.1,1257.9,310726,-65.0,Wang Yupu,Petroleum Refining,Energy,4,China,"Beijing, China",http://www.sinopec.com,19,713288,106523
China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining,Energy,3,China,"Beijing, China",http://www.cnpc.com.cn,17,1512048,301893
Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210

In [8]:
f500.index.name = None
f500_head = f500.head(10)
f500.head()

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers,Retailing,1,USA,"Bentonville, AR",http://www.walmart.com,23,2300000,77798
State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities,Energy,2,China,"Beijing, China",http://www.sgcc.com.cn,17,926067,209456
Sinopec Group,3,267518,-9.1,1257.9,310726,-65.0,Wang Yupu,Petroleum Refining,Energy,4,China,"Beijing, China",http://www.sinopec.com,19,713288,106523
China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining,Energy,3,China,"Beijing, China",http://www.cnpc.com.cn,17,1512048,301893
Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210

In [3]:
f500_head.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Walmart to Exxon Mobil
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   rank                      10 non-null     int64
 1   revenues                  10 non-null     int64
 2   revenue_change            10 non-null     float64
 3   profits                   10 non-null     float64
 4   assets                    10 non-null     int64
 5   profit_change             8 non-null      float64
 6   ceo                       10 non-null     object
 7   industry                  10 non-null     object
 8   sector                    10 non-null     object
 9   previous_rank             10 non-null     int64
 10  country                   10 non-null     object
 11  hq_location               10 non-null     object
 12  website                   10 non-null     object
 13  years_on_global_500_list  10 non-null     int64
 14  employees                 10 non-null     int64
 15  total_stockholder_equity  10 non-null     int64
dtypes: float64(3), int64(7), object(6)
memory usage: 1.3+ KB

In [9]:
rank_change = f500['previous_rank'] - f500['rank']
print(rank_change)

Walmart                             0
State Grid                          0
Sinopec Group                       1
China National Petroleum           -1
Toyota Motor                        3
                                 ...
Teva Pharmaceutical Industries   -496
New China Life Insurance          -70
Wm. Morrison Supermarkets         -61
TUI                               -32
AutoNation                       -500
Length: 500, dtype: int64

- `Series.max()`
- Series.min()
- Series.mean()
- Series.median()
- Series.mode()
- Series.sum()

In [10]:
rank_change =  f500["previous_rank"] - f500["rank"]
rank_change_max = rank_change.max()
rank_change_min = rank_change.min()

In [11]:
rank_desc = f500['rank'].describe()

prev_rank_desc = f500['previous_rank'].describe()

In [12]:
## 5
previous_rank = f500['previous_rank']
zero_previous_rank = previous_rank.value_counts().loc[0]

In [13]:
max_f500 = f500.max(numeric_only=True)

In [14]:
# 07 
# print(f500.describe(include=['O']))
f500_desc = f500.describe()

In [15]:
# 08
f500.loc['Dow Chemical', 'ceo'] = 'Jim Fitterling'

In [16]:
# 09
motor_bool = f500['industry'] == 'Motor Vehicles and Parts'
motor_countries = f500.loc[motor_bool, 'country']

print(motor_countries.value_counts())

Japan          10
China           7
Germany         6
South Korea     3
France          3
USA             2
India           1
Canada          1
Sweden          1
Name: country, dtype: int64

In [19]:
# import numpy
# 10
prev_rank_before = f500["previous_rank"].value_counts(dropna=False).head()
zero_values  = f500['previous_rank'] == 0
f500.loc[zero_values, 'previous_rank'] = np.nan
prev_rank_after = f500['previous_rank'].value_counts(dropna=False).head()

In [20]:
# 11
f500['rank_change'] = f500['previous_rank'] - f500['rank']

rank_change_desc = f500['rank_change'].describe()

In [ ]:
# 12
usa = f500['country'] == 'USA'
china = f500['country'] == 'China'

industry_usa = f500.loc[usa, 'industry'].value_counts().head(2)
sector_china = f500.loc[china, 'sector'].value_counts().head(3)